# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=20)),
                ('olid', models.CharField(max_length=20)),
                ('lccn', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('publish_date', models.CharField(max_length=30)),
                ('number_of_pages', models.CharField(max_length=10)),
                ('subjects', models.CharField(max_length=5000)),
                ('openlibrary_medcover_url', models.CharField(max_length=500)),
                ('openlibrary_preview_url', models.CharField(max_length=500)),
                ('openlibrary_description', models.TextField(default=None)),
                ('dewey_decimal_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Location'),
        ),
    ]
